server: 
  port: 8082
spring:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
      jedis:
        pool:
          #最大连接数
          max-active: 1024
          #最大阻塞等待时间(负数表示没限制)
          max-wait: 20000
          #最大空闲
          max-idle: 200
          #最小空闲
          min-idle: 10
      #连接超时时间
      timeout: 10000